INSERT INTO OM_PRODUCT_INVENTORY (product_id,QUANTITY, CREATION_DATE, LAST_UPDATED_DATE)
VALUES (1,15, sysdate, sysdate);
INSERT INTO OM_PRODUCT_INVENTORY (product_id,QUANTITY, CREATION_DATE, LAST_UPDATED_DATE)
VALUES (2,5, sysdate, sysdate);
INSERT INTO OM_PRODUCT_INVENTORY (product_id,QUANTITY, CREATION_DATE, LAST_UPDATED_DATE)
VALUES (3,8, sysdate, sysdate);
INSERT INTO OM_PRODUCT_INVENTORY (product_id,QUANTITY, CREATION_DATE, LAST_UPDATED_DATE)
VALUES (4,2, sysdate, sysdate);
INSERT INTO OM_PRODUCT_INVENTORY (product_id,QUANTITY, CREATION_DATE, LAST_UPDATED_DATE)
VALUES (5,1, sysdate, sysdate);