FROM openjdk:8
COPY target/om-product-service-0.0.1-SNAPSHOT.jar /opt/lib/
# ENTRYPOINT ["/usr/bin/java"]
# ENTRYPOINT ["/opt/java/openjdk/"]
CMD ["echo","$JAVA_HOME"]
CMD ["java","-version"]
CMD ["java","-jar","/opt/lib/om-product-service-0.0.1-SNAPSHOT.jar"]
EXPOSE 9100 9101